services:
  app:
    image: node:24.16-alpine3.22
    network_mode: host
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c 'npm install && npm run dev'

  test:
    image: node:24.16-alpine3.22
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c 'npm install && npm run test'
