version: "3.9"
services:
  kf_arranger:
    image: node:20-alpine3.18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c 'npm install && npm run cbs'
    profiles:
      - dev
    ports:
      - "5050:5050"
  kf_arranger_with_local_es:
    image: node:20-alpine3.18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c 'npm install && npm run cbs'
    profiles:
      - dev_with_local_es
    ports:
      - "5050:5050"
    networks:
      - es-net
  kf_arranger_test:
    image: node:20-alpine3.18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c 'npm install && npm run test'
    profiles:
      - test
networks:
  es-net:
    external: true