import Ajv from 'ajv';

export const mockStudies = [
    {
        dataset: [
            {
                dataset_id: 'HTP-TR',
                external_dataset_id: '',
                dataset_name: 'HTP Whole Blood RNAseq (v1)',
                date_collection_start_year: '2016',
                date_collection_end_year: '2020',
                data_category: 'Transcriptomics',
                data_types: ['Normalized relative expression (FPKM)'],
                expected_number_participants: 400,
                experimental_strategy: 'Bulk polyA+ RNAseq',
                experimental_platform: 'Illumina Novaseq',
                is_harmonized: true,
                publications: ['PMID: 37379383'],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: '',
                repository: 'Gene Expression Omnibus',
                repository_url: 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE190125',
                participant_count: 400,
                biospecimen_count: 402,
                file_count: 3200,
            },
            {
                dataset_id: 'HTP-MET',
                external_dataset_id: '',
                dataset_name: 'HTP Plasma Metabolomics (v1)',
                date_collection_start_year: '2016',
                date_collection_end_year: '2020',
                data_category: 'Metabolomics',
                data_types: ['Preprocessed metabolite relative abundance'],
                expected_number_participants: 418,
                experimental_strategy: 'LCMS Metabolomics',
                experimental_platform: 'Ultra high-performance liquid chromatography-mass spectrometry (UHPLC-MS)',
                is_harmonized: false,
                publications: ['PMID: 37379383'],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: 'phs002981',
                repository: 'Metabolomics Workbench',
                repository_url:
                    'http://dev.metabolomicsworkbench.org:22222/data/DRCCMetadata.php?Mode=Study&StudyID=ST002200&Access=UrlT3545',
                participant_count: 418,
                biospecimen_count: 3743,
                file_count: 418,
            },
            {
                dataset_id: 'HTP-UNHAR',
                external_dataset_id: '',
                dataset_name: 'HTP Unharmonized Demographic/Clinical Data',
                date_collection_start_year: '2016',
                date_collection_end_year: '',
                data_category: 'Unharmonized Demographic/Clinical Data',
                data_types: [],
                expected_number_participants: 1055,
                experimental_strategy: '',
                experimental_platform: '',
                is_harmonized: false,
                publications: ['PMID: 37379383'],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: '',
                repository: '',
                repository_url: '',
                participant_count: 1055,
                biospecimen_count: 0,
                file_count: 1,
            },
            {
                dataset_id: 'HTP-PRO',
                external_dataset_id: '',
                dataset_name: 'HTP Plasma Inflammatory Markers (MSD v1)',
                date_collection_start_year: '2016',
                date_collection_end_year: '2020',
                data_category: 'Proteomics',
                data_types: ['Protein abundance (absolute protein concentration)'],
                expected_number_participants: 477,
                experimental_strategy: 'Multiplex immunoassay',
                experimental_platform: 'Meso Scale Discovery Assays (MSD)',
                is_harmonized: false,
                publications: ['PMID: 37379383'],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: '',
                repository: 'Synapse',
                repository_url: 'https://www.synapse.org/#!Synapse:syn31475487',
                participant_count: 477,
                biospecimen_count: 4371,
                file_count: 477,
            },
        ],
        date_collection_end_year: '',
        date_collection_start_year: '2016',
        institutions: ['Linda Crnic Institute for Down Syndrome'],
        investigator_names: ['Joaquin M. Espinosa'],
        study_code: 'HTP',
    },
    {
        dataset: [
            {
                dataset_id: 'DS-COG-ALL-GEN',
                external_dataset_id: '',
                dataset_name: 'DS-COG-ALL Whole Genome Sequencing',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Genomics',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 530,
                experimental_strategy: 'Whole Genome Sequencing',
                experimental_platform: 'Illumina',
                is_harmonized: true,
                publications: [],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: 'phs002330',
                repository: '',
                repository_url: '',
                participant_count: 530,
                biospecimen_count: 834,
                file_count: 7407,
            },
            {
                dataset_id: 'DS-COG-ALL-UNHAR',
                external_dataset_id: '',
                dataset_name: 'DS-COG-ALL Unharmonized Demographic/Clinical Data',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Unharmonized Demographic/Clinical Data',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 530,
                experimental_strategy: '',
                experimental_platform: '',
                is_harmonized: false,
                publications: [],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: 'phs002330',
                repository: '',
                repository_url: '',
                participant_count: 530,
                biospecimen_count: 0,
                file_count: 1,
            },
        ],
        date_collection_end_year: '',
        date_collection_start_year: '',
        institutions: ['Baylor College Of Medicine'],
        investigator_names: ['Phillip J. Lupo'],
        study_code: 'DS-COG-ALL',
    },
    {
        dataset: [
            {
                dataset_id: 'DS360-CHD-GEN',
                external_dataset_id: '',
                dataset_name: 'DS360-CHD Whole Genome Sequencing',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Genomics',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 1327,
                experimental_strategy: 'Whole Genome Sequencing',
                experimental_platform: 'Illumina',
                is_harmonized: true,
                publications: [],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: ['not for profit organisation use only (DUO:0000045)'],
                dbgap: 'phs002330',
                repository: '',
                repository_url: '',
                participant_count: 1327,
                biospecimen_count: 1344,
                file_count: 4635,
            },
            {
                dataset_id: 'DS360-CHD-UNHAR',
                external_dataset_id: '',
                dataset_name: 'DS360-CHD Unharmonized Demographic/Clinical Data',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Unharmonized Demographic/Clinical Data',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 1327,
                experimental_strategy: '',
                experimental_platform: '',
                is_harmonized: false,
                publications: [],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: ['not for profit organisation use only (DUO:0000045)'],
                dbgap: 'phs002330',
                repository: '',
                repository_url: '',
                participant_count: 1327,
                biospecimen_count: 0,
                file_count: 1,
            },
        ],
        date_collection_end_year: '',
        date_collection_start_year: '',
        institutions: ['Emory University School of Medicine'],
        investigator_names: ['Stephanie Sherman'],
        study_code: 'DS360-CHD',
    },
    {
        dataset: [
            {
                dataset_id: 'DS-PCGC-GEN',
                external_dataset_id: '',
                dataset_name: 'DS-PCGC Whole Genome Sequencing',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Genomics',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 369,
                experimental_strategy: 'Whole Genome Sequencing',
                experimental_platform: 'Illumina',
                is_harmonized: true,
                publications: [],
                access_limitations: ['health or medical or biomedical research (DUO:0000006)'],
                access_requirements: ['not for profit organisation use only (DUO:0000045)'],
                dbgap: 'phs001138',
                repository: '',
                repository_url: '',
                participant_count: 382,
                biospecimen_count: 369,
                file_count: 901,
            },
            {
                dataset_id: 'DS-PCGC-UNHAR',
                external_dataset_id: '',
                dataset_name: 'DS-PCGC Unharmonized Demographic/Clinical Data',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Unharmonized Demographic/Clinical Data',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 369,
                experimental_strategy: '',
                experimental_platform: '',
                is_harmonized: false,
                publications: [],
                access_limitations: ['health or medical or biomedical research (DUO:0000006)'],
                access_requirements: ['not for profit organisation use only (DUO:0000045)'],
                dbgap: 'phs001138',
                repository: '',
                repository_url: '',
                participant_count: 382,
                biospecimen_count: 0,
                file_count: 1,
            },
        ],
        date_collection_end_year: '',
        date_collection_start_year: '',
        institutions: ["Cincinnati Children's Hospital Medical Center"],
        investigator_names: ['Eileen C. King'],
        study_code: 'DS-PCGC',
    },
    {
        dataset: [
            {
                dataset_id: 'X01-Hakon-GEN',
                external_dataset_id: '',
                dataset_name: 'X01-Hakonarson Whole Genome Sequencing',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Genomics',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 1134,
                experimental_strategy: 'Whole Genome Sequencing',
                experimental_platform: 'Illumina',
                is_harmonized: true,
                publications: [],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: 'phs002983',
                repository: '',
                repository_url: '',
                participant_count: 1134,
                biospecimen_count: 1908,
                file_count: 3255,
            },
            {
                dataset_id: 'X01-Hakon-RNASeq',
                external_dataset_id: '',
                dataset_name: 'X01-Hakonarson RNASeq',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Transcriptomics',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 379,
                experimental_strategy: 'Bulk RNA-Seq',
                experimental_platform: 'Illumina',
                is_harmonized: true,
                publications: [],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: 'phs002983',
                repository: '',
                repository_url: '',
                participant_count: 379,
                biospecimen_count: 1908,
                file_count: 3410,
            },
            {
                dataset_id: 'X01-Hakon-UNHAR',
                external_dataset_id: '',
                dataset_name: 'X01-Hakonarson Unharmonized Demographic/Clinical Data',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Unharmonized Demographic/Clinical Data',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 1152,
                experimental_strategy: '',
                experimental_platform: '',
                is_harmonized: false,
                publications: [],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: 'phs002983',
                repository: '',
                repository_url: '',
                participant_count: 1152,
                biospecimen_count: 0,
                file_count: 1,
            },
        ],
        date_collection_end_year: '',
        date_collection_start_year: '',
        institutions: ["Children's Hospital of Philadelphia"],
        investigator_names: ['Hakon Hakonarson'],
        study_code: 'X01-Hakonarson',
    },
    {
        dataset: [
            {
                dataset_id: 'X01-deSmith-GEN',
                external_dataset_id: '',
                dataset_name: 'X01-deSmith Whole Genome Sequencing',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Genomics',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 436,
                experimental_strategy: 'Whole Genome Sequencing',
                experimental_platform: 'Illumina',
                is_harmonized: true,
                publications: [],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: 'phs002982',
                repository: '',
                repository_url: '',
                participant_count: 436,
                biospecimen_count: 436,
                file_count: 1308,
            },
            {
                dataset_id: 'X01-deSmith-UNHAR',
                external_dataset_id: '',
                dataset_name: 'X01-deSmith Unharmonized Demographic/Clinical Data',
                date_collection_start_year: '',
                date_collection_end_year: '',
                data_category: 'Unharmonized Demographic/Clinical Data',
                data_types: [],
                expected_data_categories: [],
                expected_number_participants: 436,
                experimental_strategy: '',
                experimental_platform: '',
                is_harmonized: false,
                publications: [],
                access_limitations: ['general research use (DUO:0000042)'],
                access_requirements: [],
                dbgap: 'phs002982',
                repository: '',
                repository_url: '',
                participant_count: 436,
                biospecimen_count: 436,
                file_count: 1,
            },
        ],
        date_collection_end_year: '',
        date_collection_start_year: '',
        institutions: ['University of Oxford'],
        investigator_names: ['Adam de Smith'],
        study_code: 'X01-deSmith',
    },
    {
        dataset: [],
        date_collection_end_year: '',
        date_collection_start_year: '2018',
        institutions: ['Benaroya Research Institute'],
        investigator_names: ['Jane Buckner'],
        study_code: 'BRI-DSR',
    },
    {
        dataset: [],
        date_collection_end_year: '',
        date_collection_start_year: '',
        institutions: ['Linda Crnic Institute for Down Syndrome'],
        investigator_names: ['Joaquin Espinosa'],
        study_code: 'DS-NEXUS',
    },
    {
        dataset: [],
        date_collection_end_year: '',
        date_collection_start_year: '',
        institutions: ['Geisinger Health System'],
        investigator_names: ['Christa Martin'],
        study_code: 'DS-Sleep',
    },
    {
        dataset: [
            {
                dataset_id: 'DS-Connect-UNHAR',
                external_dataset_id: '',
                dataset_name: 'DS-Connect Unharmonized Demographic/Clinical Data',
                date_collection_start_year: '2013',
                date_collection_end_year: '',
                data_category: 'Unharmonized Demographic/Clinical Data',
                data_types: ['Social Determinants of Health', 'Demographics', 'Co-occurring Conditions'],
                expected_data_categories: ['Unharmonized Demographic/Clinical Data'],
                expected_number_participants: 3634,
                experimental_strategy: '',
                experimental_platform: '',
                is_harmonized: false,
                publications: [],
                access_limitations: [],
                access_requirements: [],
                dbgap: '',
                repository: '',
                repository_url: '',
                participant_count: 3634,
                biospecimen_count: 0,
                file_count: 1,
            },
        ],
        date_collection_end_year: '',
        date_collection_start_year: '2013',
        institutions: ['Eunice Kennedy Shriver National Institute of Child Health and Human Development'],
        investigator_names: ['Sujata Bardhan'],
        study_code: 'DSC',
    },
    {
        dataset: [],
        date_collection_end_year: '',
        date_collection_start_year: '',
        institutions: ['University of Pittsburgh'],
        investigator_names: ['Bradley T. Christian', 'Benjamin L. Handen', 'Elizabeth Head', 'Mark Mapstone'],
        study_code: 'ABC-DS',
    },
];

const sSchema = {
    title: 'Study',
    type: 'object',
    properties: {
        dataset: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    dbgap: {
                        type: 'string',
                    },
                    dataset_id: {
                        type: 'string',
                    },
                    external_dataset_id: {
                        type: 'string',
                    },
                    dataset_name: {
                        type: 'string',
                    },
                    date_collection_start_year: {
                        type: 'string',
                    },
                    date_collection_end_year: {
                        type: 'string',
                    },
                    data_category: {
                        type: 'string',
                    },
                    data_types: {
                        type: 'array',
                        items: {
                            type: 'string',
                        },
                    },
                    expected_number_participants: {
                        type: 'integer',
                    },
                    experimental_strategy: {
                        type: 'string',
                    },
                    experimental_platform: {
                        type: 'string',
                    },
                    publications: {
                        type: 'array',
                        items: {
                            type: 'string',
                        },
                    },
                    access_limitations: {
                        type: 'array',
                        items: {
                            type: 'string',
                        },
                    },
                    access_requirements: {
                        type: 'array',
                        items: {
                            type: 'string',
                        },
                    },
                    repository: {
                        type: 'string',
                    },
                    repository_url: {
                        type: 'string',
                    },
                    participant_count: {
                        type: 'integer',
                    },
                    biospecimen_count: {
                        type: 'integer',
                    },
                    file_count: {
                        type: 'integer',
                    },
                    is_harmonized: {
                        type: 'boolean',
                    },
                },
            },
        },
        date_collection_end_year: {
            type: 'string',
        },
        date_collection_start_year: {
            type: 'string',
        },
        institutions: {
            type: 'array',
            items: {
                type: 'string',
            },
        },
        investigator_names: {
            type: 'array',
            items: {
                type: 'string',
            },
        },
        study_code: {
            type: 'string',
        },
    },
    required: ['study_code'],
};

export const validateStudies = sData => {
    const ajv = new Ajv();
    const validate = ajv.compile(sSchema);
    return sData.map(s => {
        const valid = validate(s);
        return [s.study_code, valid, validate.errors];
    });
};
